# Generated by Django 4.0.1 on 2022-01-25 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0006_remove_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='blood_group',
        ),
    ]
