# Generated by Django 4.0.1 on 2022-01-25 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edu_app', '0007_remove_student_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A +ve', 'A +'), ('B +ve', 'B +'), ('AB +ve', 'AB +'), ('O +ve', 'O +'), ('O -ve', 'O -')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
