# Generated by Django 4.0.1 on 2022-01-25 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0008_student_blood_group_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
