# Generated by Django 4.0.1 on 2022-01-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0009_remove_student_blood_group_remove_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A +ve', 'A +'), ('B +ve', 'B +'), ('AB +ve', 'AB +'), ('O +ve', 'O +'), ('O -ve', 'O -')], max_length=10, null=True),
        ),
    ]
