# Generated by Django 4.0.1 on 2022-01-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0013_remove_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='prof',
            field=models.ImageField(default='', upload_to='edu_app/images'),
        ),
    ]
