# Generated by Django 4.0.1 on 2022-01-28 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0020_staff_is_staff_student_is_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_student',
        ),
    ]
