# Generated by Django 4.0.1 on 2022-01-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0021_remove_staff_is_staff_remove_student_is_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField(max_length=250)),
                ('file', models.FileField(upload_to='edu_app/assignments')),
                ('deadline', models.DateTimeField()),
                ('date_posted', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
