# Generated by Django 4.0.1 on 2022-02-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0024_message_date_posted_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A +ve'), ('B+', 'B +ve'), ('AB+', 'AB +ve'), ('O+', 'O +ve'), ('O-', 'O -ve'), ('AB-', 'AB-ve')], max_length=4, null=True),
        ),
    ]
